# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.14.0'

In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/200529495/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/200529495/AppData/Local/Continuum/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/200529495/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program File

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
data = np.zeros(10)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
data.nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
data = np.zeros(10)
data[4] = 1
data

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
data = np.arange(10,50)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
data[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [11]:
data = np.array([1,2,0,0,4,0])
data.nonzero()

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
data = np.eye(3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
data = np.random.randn(3,3,3)
data

array([[[ 0.08162991,  0.03590151, -0.28360439],
        [ 0.40109467, -1.18969399,  0.09289063],
        [ 1.65487853,  0.43339047, -0.68177511]],

       [[-1.48285016,  1.60575522, -1.74563658],
        [ 0.74456541, -0.63567493, -2.43852916],
        [ 2.30559742,  0.24261613,  0.28680504]],

       [[-0.36935364,  0.15009446,  0.94602689],
        [ 1.10832522,  0.37377209, -1.15601361],
        [ 0.07307278, -3.27141847,  2.21993687]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
data = np.random.randn(10,10)
datamin, datamax = data.min(), data.max()
print(datamin, datamax)

-2.11083428884848 2.085478042603088


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
data = np.random.randn(30)
data.mean()

-0.03216872256623269

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
data = np.ones([5,5])
data[1:-1,1:-1]=0
data

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
data = np.ones([5,5])
np.pad(data, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [18]:
0 * np.nan

nan

In [19]:
np.nan == np.nan

False

In [20]:
np.inf > np.nan

False

In [21]:
np.nan - np.nan

nan

In [22]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
data = np.diag(1+np.arange(4), k=-1)
data

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [24]:
data = np.zeros([8,8])
data[1::2,::2] = 1
data[::2,1::2] = 1
data

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [25]:
np.unravel_index(100,(6,7,8), 'C')

(1, 5, 4)

In [26]:
np.unravel_index(100,(6,7,8), 'F')

(4, 2, 2)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [27]:
data = np.ones([2,2])
data = data - np.eye(2)
np.tile(data,[4,4])

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [28]:
data = np.random.randn(5,5)
dmin, dmax = data.min(), data.max()
(data - dmin) / (dmax - dmin)

array([[0.44685012, 0.69944297, 0.71825756, 0.        , 0.43841412],
       [0.62610032, 0.64238897, 0.30247598, 0.70713923, 0.41431077],
       [0.29966302, 0.26591129, 0.28012162, 0.49615912, 0.33045946],
       [0.38661088, 0.6333009 , 0.49699204, 0.41561989, 0.63848295],
       [0.31418672, 1.        , 0.51640544, 0.34438906, 0.14533785]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [29]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [30]:
d1 = np.random.randn(5,3)
d2 = np.random.randn(3,2)
d1 @ d2

array([[-2.65376647,  1.57979969],
       [ 1.41112615,  1.25082543],
       [-1.03654431, -4.25411332],
       [ 2.1750183 , -1.8653984 ],
       [ 2.30051364,  1.8948205 ]])

In [31]:
d1.dot(d2)

array([[-2.65376647,  1.57979969],
       [ 1.41112615,  1.25082543],
       [-1.03654431, -4.25411332],
       [ 2.1750183 , -1.8653984 ],
       [ 2.30051364,  1.8948205 ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [32]:
data = np.arange(11)
data[(data >= 3) & (data <= 8)] *= -1
data

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
sum(range(5))

10

In [34]:
sum(range(5),-1)

9

In [35]:
sum(range(5),1)

11

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [36]:
Z = np.array([0,1,2])

Z**Z        # 0^0, 1^1, 2^2
2 << Z << 2 # bit shift operators
            # x << z => x*x^z
            # x >> z => x/x^z
Z <- Z      # Z < (-Z)

array([False, False, False])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [37]:
np.array(0) / np.array(0) # nan
np.array(0) // np.array(0) # 0
np.array([np.nan]).astype(int).astype(float)

C:\Users\200529495\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\200529495\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [38]:
data = np.random.uniform(-10, +10, 10)
print(data)
print(np.copysign(np.ceil(np.abs(data)), data))

[-1.62059489  5.71517334  5.92747582 -5.31765124 -2.63707024  3.5487534
 -5.85268192  6.12741869 -7.85056703 -1.52614776]
[-2.  6.  6. -6. -3.  4. -6.  7. -8. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [39]:
d1 = np.random.randint(0,10,10)
d1

array([3, 3, 5, 7, 7, 3, 2, 7, 8, 8])

In [40]:
d2 = np.random.randint(0,10,10)
d2

array([0, 2, 7, 4, 5, 0, 5, 0, 7, 8])

In [41]:
np.intersect1d(d1,d2)

array([2, 5, 7, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [42]:
np.seterr(all="ignore")
np.ones(1)/0

array([inf])

In [43]:
np.seterr(all="warn")
np.ones(1)/0

C:\Users\200529495\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([inf])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [44]:
np.sqrt(-1) == np.emath.sqrt(-1) # False
# np.sqrt(-1) => nan
# np.emath.sqrt(-1) => 1j

C:\Users\200529495\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
np.datetime64('today','D')
# D => day, M=> month, Y=> year
# m => minute, s => second

numpy.datetime64('2018-04-06')

In [46]:
np.datetime64('today') - np.timedelta64(1)

numpy.datetime64('2018-04-05')

In [47]:
np.datetime64('today') + np.timedelta64(1)

numpy.datetime64('2018-04-07')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [48]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [49]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(B,A,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [50]:
data = np.random.uniform(-10,10,5)
dabs = np.abs(data)
data

array([ 9.05964854,  4.80614925, -0.55428792,  9.71260559, -3.66788377])

In [51]:
np.copysign((dabs - dabs%1), data)

array([ 9.,  4., -0.,  9., -3.])

In [52]:
np.copysign(np.floor(dabs), data)

array([ 9.,  4., -0.,  9., -3.])

In [53]:
np.copysign(np.ceil(dabs)-1, data)

array([ 9.,  4., -0.,  9., -3.])

In [54]:
data.astype(int)
# BEST

array([ 9,  4,  0,  9, -3])

In [55]:
np.trunc(data)

array([ 9.,  4., -0.,  9., -3.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [56]:
data = np.zeros((5,5))
data += np.arange(5)
data

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [57]:
def generate():
    for x in range(10):
        yield x
# yield : like return
        
data = np.fromiter(generate(),dtype=int)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [58]:
data = np.linspace(0, 1, num=11, endpoint=False)[1:]
data

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [59]:
data = np.random.randn(10)
data.sort()
data

array([-0.83198182, -0.79641255, -0.66251617, -0.52749108, -0.52682453,
       -0.16329089, -0.09320714,  0.07620586,  0.32193614,  0.98173706])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [60]:
data = np.arange(10)
np.add.reduce(data)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [61]:
d1 = np.random.randint(0,5,3)
d1

array([4, 4, 4])

In [62]:
d2 = np.random.randint(0,5,3)
d2

array([2, 3, 3])

In [63]:
np.equal(d1,d2)

array([False, False, False])

In [64]:
np.array_equal(d1,d2)

False

In [65]:
np.allclose(d1,d2) # tolerance value = 0

False

#### 43. Make an array immutable (read-only) (★★☆)

In [66]:
data = np.arange(3)
data.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [67]:
data = np.random.randint(-20,20,size=20).reshape(10,2)
x, y = data[:,0], data[:,1]
data

array([[  5,  11],
       [ -3,  -4],
       [  7,  -1],
       [  6,  -3],
       [ 19,  -3],
       [-12, -19],
       [ 10,   5],
       [  1,   8],
       [ 17,  14],
       [-15, -12]])

In [68]:
import math
d1 = np.sqrt(x**2 + y**2)
d2 = np.arctan2(y, x)*180/math.pi
data[:,0], data[:,1] = d1, d2
data

array([[  12,   65],
       [   5, -126],
       [   7,   -8],
       [   6,  -26],
       [  19,   -8],
       [  22, -122],
       [  11,   26],
       [   8,   82],
       [  22,   39],
       [  19, -141]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [69]:
data = np.random.randn(10)
data

array([-0.64551839, -0.56268567, -0.66566721, -1.31770265,  0.65969189,
       -0.18737367, -0.7841067 , -0.00545967, -0.64724026, -1.06211979])

In [70]:
data[data.argmax()] = 0
data

array([-0.64551839, -0.56268567, -0.66566721, -1.31770265,  0.        ,
       -0.18737367, -0.7841067 , -0.00545967, -0.64724026, -1.06211979])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [71]:
data = np.zeros((5,5),[('x',float),('y',float)])
x = np.linspace(0,1,5)
data['x'], data['y'] = np.meshgrid(x, x)
data

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [72]:
d1 = np.arange(5)
d2 = d1 + 0.5
C = 1 / np.subtract.outer(d1, d2)
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [73]:
for dtype in [np.int8, np.int16, np.int32]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    # machine epsilon是计算机中最小的浮点数
    # 使得满足关系1 + machine epsilon = 1
    # 也可理解为此数是计算机浮点运算中的精度

-128
127
-32768
32767
-2147483648
2147483647
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [74]:
np.set_printoptions(threshold=19)
data = np.arange(20)
print(data)

[ 0  1  2 ... 17 18 19]


In [75]:
np.set_printoptions(threshold=20)
data = np.arange(20)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [76]:
np.set_printoptions(threshold=21)
data = np.arange(20)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [77]:
np.set_printoptions(threshold=np.nan)
data = np.arange(20)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [78]:
data = np.arange(100)
sdata = np.random.uniform(0,100)
index = (np.abs(data-sdata)).argmin()
data[index]

97

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [79]:
data = np.zeros(10, [
    ('position',[('x',float,1),
                ('y',float,1)]),
    ('color',[('r',float,1),
             ('g',float,1),
             ('b',float,1)])
    
])
data

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [84]:
data = np.random.randn(10,2)
x, y = np.atleast_2d(data[:,0], data[:,1])


array([[ 0.85261026, -0.37075689,  0.69655887,  0.28577622,  0.23335471,
        -0.23923648,  0.98262806, -1.92804007,  1.01214651, -0.17651016]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)